### PR TITLE
More useless cleaning up and iPSE offsets

### PR DESCRIPTION
**Pull request by McGamezZPlayer**
Allow to be blind, too, callbacks is an actual offset.

### CODE REVIEW

**Comment by nn9dev** [comment]
hA I was actually about to attempt to get 12.0 iPhone SE offsets myself! You beat me to it!

**Comment by Lucaiii** [comment]
hey, noticed your commit is for 12.0.1, whereas these are for 12.0! (checked them on my SE)

**Comment by Lucaiii** [comment]
Yup, it's all good. Just saying you should change it.

**Comment by McGamezZPlayer** [comment]
I am not because they are the same between the two version, I believe, just like with how 11.3.1 are the same as 11.3

**Comment by userlandkernel** [comment]
Thanx

**Pull request merged**
